### ISSUE TITLE
Tampermonkey

### ISSUE THREAD

**Issue by Medivha** [folderolsoftware/PoE-Flow#1]
Doesn't work with Tampermonkey

https://i.imgur.com/XO8BAU0.png

invalid userscript on save

**Comment by folderolsoftware** [comment]
I'll upload a separate Tampermonkey version shortly!

**Comment by folderolsoftware** [comment]
https://raw.githubusercontent.com/folderolsoftware/PoE-Flow/refs/heads/main/dist/BetterBulkFilter.user.js should work with Tampermonkey & Userscripts for Safari, I'll update the Reddit post with this as well. It has a few extra unused methods in it because I need to fix my build process, but I'd rather get back to the game for now :D Cheers!
